### ISSUE TITLE
Does not seem to be pulling today's image

### ISSUE THREAD

**Issue by jacktuck** [cseale/hypernasa#4]
Has been working fine until now, no errors or anything in dev console.

Anything i can do to get more debug info to send over?

**Comment by jacktuck** [comment]
No images loaded in network tab either

**Comment by cseale** [comment]
Unless there is some issue with today's image... I will take a look later after work. That's enough info for me, thanks for the heads up! :D You are always welcome to fork the repo and take a deeper look yourself!

**Comment by jacktuck** [comment]
#5

**Comment by jux-t** [comment]
Found a fix. The image is downloading from the server but:

In ```div.hyper_main```:

```css
background-image: url(https://apod.nasa.gov/apod/image/1701/vdB142_L(HaR)GB-finalLeshin2048.jpg)
```
has no quote marks around the URL, thus the renderer is not parsing the URL correctly (I would assume it's that ```(HAR)``` piece.

Fix:
```css
.hyper_main {
background-image: url("https://apod.nasa.gov/apod/image/1701/vdB142_L(HaR)GB-finalLeshin2048.jpg");
}
